package com.tamj0rd2.ktcheck.contract

import com.tamj0rd2.ktcheck.producer.Seed
import kotlin.random.Random

internal interface IGen<T> {
    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): IGen<R>

    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> = seeds(seed).map { sample(it.value) }
}

internal fun seeds(start: Long = Random.nextLong()) =
    generateSequence(Seed(start)) { it.next(0) }
