package com.tamj0rd2.ktcheck.v2

import com.tamj0rd2.ktcheck.producer.ProducerTree
import com.tamj0rd2.ktcheck.producer.Seed
import kotlin.random.Random
import kotlin.random.nextInt

internal data class GenContext(
    val producer: ValueProducer,
)

interface ValueProducer {
    fun int(range: IntRange): Int
    fun bool(): Boolean
}

class RandomValueProducer internal constructor(seed: Seed) : ValueProducer {
    private val random: Random = Random(seed.value)

    override fun int(range: IntRange): Int = random.nextInt(range)

    override fun bool(): Boolean = random.nextBoolean()
}

/**
 * A generator that can produce values of type T.
 *
 * @param T The type of values produced by this generator.
 */
sealed class Gen<T> {
    internal abstract fun GenContext.generate(): GenResult<T>

    internal fun generate(producer: ValueProducer): GenResult<T> = GenContext(producer).generate()

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): Gen<R> = BasicGenerator { generate().map(fn) }

    companion object {
        internal fun seeds(start: Long = Random.nextLong()) =
            generateSequence(Seed(start)) { it.next(0) }

        /**
         * Produces an infinite sequence of samples from the generator using the provided seed.
         *
         * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
         * @return A sequence of sampled values of type T.
         */
        fun <T> Gen<T>.samples(seed: Long = Random.nextLong()): Sequence<T> =
            seeds(seed).map { sample(it.value) }

        /**
         * Samples a value from the generator using the provided seed.
         *
         * @param seed The seed to use for sampling.
         * @return A sampled value of type T.
         */
        fun <T> Gen<T>.sample(seed: Long): T = generate(RandomValueProducer(Seed(seed))).value

        internal fun <T> Gen<T>.sample(producer: ValueProducer): T = generate(producer).value
    }
}

/**
 * The result of generating a value from a generator, including the generated value and its shrinks.
 * Shrinks are represented as a sequence of [ProducerTree]s, allowing for lazy evaluation and efficient traversal.
 */
internal data class GenResult<T>(val value: T, val shrinks: Sequence<GenResult<T>>) {
    fun <R> map(fn: (T) -> R): GenResult<R> = GenResult(
        value = fn(value),
        shrinks = shrinks.map { it.map(fn) },
    )
}

private class BasicGenerator<T>(
    private val generateFn: GenContext.() -> GenResult<T>,
) : Gen<T>() {
    override fun GenContext.generate(): GenResult<T> = generateFn()
}
