package com.tamj0rd2.ktcheck

import com.tamj0rd2.ktcheck.core.Seed
import kotlin.random.Random

/**
 * A generator that can produce values of type T.
 */
interface Gen<T> {
    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): Gen<R>

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     * The resulting generator is then used to generate the final value.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a generator that depends on the value produced by another generator.
     * If you instead want to combine two independent generators, consider using [plus] or [combineWith].
     *
     * @param fn A function that takes a value of type T and returns a generator of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> flatMap(fn: (T) -> Gen<R>): Gen<R>

    /**
     * Combines two independent generators using the provided combining function.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a new generator that produces values based on two independent generators. i.e
     * the value from one generator does not influence the value from the other generator.
     *
     * @param nextGen The second generator to combine with this generator.
     * @param combine A function that takes values from both generators and combines them into a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <T2, R> combineWith(nextGen: Gen<T2>, combine: (T, T2) -> R): Gen<R>

    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> = Seed.sequence(seed).map { sample(it.value) }
}

sealed class GenerationException(message: String, cause: Throwable? = null) : IllegalStateException(message, cause) {
    class OneOfEmpty internal constructor() : GenerationException("Gen.oneOf() called with no generators")

    class FilterLimitReached internal constructor(threshold: Int, cause: Throwable?) :
        GenerationException("Filter failed after $threshold misses", cause)

    class DistinctCollectionSizeImpossible internal constructor(targetSize: Int, achievedSize: Int, attempts: Int) :
        GenerationException(
            "Failed to generate a list of size $targetSize with distinct elements after $attempts attempts. Only achieved size $achievedSize."
        )
}
