package com.tamj0rd2.ktcheck

import com.tamj0rd2.ktcheck.gen.GenV1
import com.tamj0rd2.ktcheck.producer.Seed
import kotlin.random.Random

interface Gen<T> {
    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): Gen<R>

    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> = Seed.sequence(seed).map { sample(it.value) }

    companion object : GenBuilder by GenV1.Companion
}

sealed class GenerationException(message: String, cause: Throwable? = null) : IllegalStateException(message, cause) {
    class OneOfEmpty internal constructor() : GenerationException("Gen.oneOf() called with no generators")

    class FilterLimitReached internal constructor(threshold: Int, cause: Throwable?) :
        GenerationException("Filter failed after $threshold misses", cause)

    class DistinctCollectionSizeImpossible internal constructor(targetSize: Int, achievedSize: Int, attempts: Int) :
        GenerationException(
            "Failed to generate a list of size $targetSize with distinct elements after $attempts attempts. Only achieved size $achievedSize."
        )
}
