package com.tamj0rd2.ktcheck.core

import com.tamj0rd2.ktcheck.core.GenerationException.OneOfEmpty
import com.tamj0rd2.ktcheck.gen.CombinerContext
import com.tamj0rd2.ktcheck.gen.GenV1
import com.tamj0rd2.ktcheck.producer.Seed
import java.util.*
import kotlin.random.Random
import kotlin.reflect.KClass

interface IGen<T> {
    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): IGen<R>

    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> = seeds(seed).map { sample(it.value) }
}

interface GenBuilder {
    fun <T> constant(value: T): IGen<T>

    fun bool(): IGen<Boolean>

    fun int(range: IntRange = Int.MIN_VALUE..Int.MAX_VALUE): IGen<Int>

    fun long(range: IntRange = Int.MIN_VALUE..Int.MAX_VALUE): IGen<Long>

    // todo: I can implement it here once I have a basic combinator generator
    fun uuid(): IGen<UUID>

    fun char(
        chars: Iterable<Char> = Char.MIN_VALUE..Char.MAX_VALUE,
    ): IGen<Char> = oneOf(chars.distinct().sorted())

    /** Shrinks towards the first generator */
    fun <T> oneOf(vararg gens: IGen<T>): IGen<T> = oneOf(gens.toList())

    /** Shrinks toward the first generator */
    fun <T> oneOf(gens: Collection<IGen<T>>): IGen<T>

    /** Shrinks toward the first value. Individual values will not be shrunk. */
    fun <T> oneOf(values: Iterable<T>): IGen<T> {
        val options = values.toList()
        if (options.isEmpty()) throw OneOfEmpty()
        return int(0..<options.size).map { options[it] }
    }

    // todo: at this point, some kind of builder would help with optional parameters
    fun <T> IGen<T>.list(size: IntRange = 0..100, distinct: Boolean = false): IGen<List<T>>

    fun <T> IGen<T>.list(size: Int, distinct: Boolean = false): IGen<List<T>> =
        list(size..size, distinct)

    fun <T> IGen<T>.set(size: IntRange = 0..100): IGen<Set<T>> =
        list(size, distinct = true).map { it.toSet() }

    fun <T> IGen<T>.set(size: Int): IGen<Set<T>> =
        set(size..size)

    fun IGen<Char>.string(size: IntRange): IGen<String>

    fun IGen<Char>.string(size: Int): IGen<String>

    fun <T> IGen<T>.filter(predicate: (T) -> Boolean): IGen<T> = filter(100, predicate)

    fun <T> IGen<T>.filter(threshold: Int, predicate: (T) -> Boolean): IGen<T>

    fun <T> IGen<T>.ignoreExceptions(klass: KClass<out Exception>, threshold: Int = 100): IGen<T>

    /**
     * Combines multiple generators into a single generator using a builder-style DSL.
     * Each generator in the block is bound sequentially, and their shrinks are combined.
     *
     * Example:
     * ```
     * val gen = Gen.combine {
     *     val x = Gen.int().bind()
     *     val y = Gen.int().bind()
     *     x to y
     * }
     * ```
     *
     * This is equivalent to using [plus] but with a more convenient syntax:
     * ```
     * val gen = (Gen.int() + Gen.bool()).map { (x, y) -> x + y }
     * ```
     *
     * **Warning about conditionals:** The combiner requires that bind functions will be called in the same order each time.
     * Conditionals that affect whether trailing [CombinerContext.bind] calls are called will shrink correctly.
     * However, conditionals that skip non-trailing [CombinerContext.bind] calls will cause invalid shrinks.
     */
    fun <T> combine(block: CombinerContext.() -> T): IGen<T>

    /**
     * Combines two independent generators into a single generator that produces a tuple of both values.
     * Shrinking is performed independently on each component.
     *
     * Example:
     * ```
     * // Gen<Pair<Int, Boolean>>
     * val gen2 = Gen.int() + Gen.boolean()
     * // Gen<Triple<Int, Boolean, String>>
     * val gen3 = Gen.int() + Gen.boolean() + Gen.string()
     * ```
     *
     * To combine more than 2 generators, use [GenV1.Companion.combine] instead.
     *
     * For dependent generation (where the second generator depends on the first value),
     * use [flatMap] or [GenV1.Companion.combine] instead.
     */
    infix operator fun <T1, T2> IGen<T1>.plus(nextGen: IGen<T2>): IGen<Pair<T1, T2>>
}

sealed class GenerationException(message: String, cause: Throwable? = null) : IllegalStateException(message, cause) {
    class OneOfEmpty internal constructor() : GenerationException("Gen.oneOf() called with no generators")

    class FilterLimitReached internal constructor(threshold: Int, cause: Throwable?) :
        GenerationException("Filter failed after $threshold misses", cause)

    class DistinctCollectionSizeImpossible internal constructor(targetSize: Int, achievedSize: Int, attempts: Int) :
        GenerationException(
            "Failed to generate a list of size $targetSize with distinct elements after $attempts attempts. Only achieved size $achievedSize."
        )
}

internal fun seeds(start: Long = Random.nextLong()) =
    generateSequence(Seed(start)) { it.next(0) }
